name: Test CF CLI Action

on:
  push:
    branches:
    - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: pdominique/cf-cli-action@master
      with:
        cf_api: ${{ secrets.CF_API }}
        cf_username: ${{ secrets.CF_USERNAME }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: ${{ secrets.CF_ORG }}
        cf_space: ${{ secrets.CF_SPACE }}
        command: target
